version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test122001"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eq8ej2shdznk"
s3_prefix = "test122001"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PJName=\"for-efs-iac\""
